### ISSUE TITLE
Interface has no text

### ISSUE THREAD

**Issue by EstherRook** [RolandDreger/indesign-openai#5]
Love the idea of this plugin. During installing it only shows the graphical elements of the interface, not the text. So you cant get past the activate interface. Would love to try this so hopefully a bug you can work on!

**Comment by RolandDreger** [comment]
Interesting. This sounds like a UXP/InDesign bug and I'm afraid there's not much I can do about it. But can you provide a screenshot so I can look into it? Which operating system and which InDesign version are you using?

**Comment by EstherRook** [comment]
Thanks for your reply! I run 19.1, it updates automatically. I work on iOS - 13.5.2 (22G91)
<img width="780" alt="indesign AI" src="https://github.com/RolandDreger/indesign-openai/assets/29239323/797a4d58-6968-439c-9873-f2e5c8bf13f4">

Attached a picture of the interface.

**Comment by RolandDreger** [comment]
It wasn't a rendering bug as first suspected. The cause was rather that your language is not defined for the translation of the UI texts. The text "Bladeren in plug-ins" at the bottom left of your screenshot put me on the right track. 🙂

The default language is now displayed. If a translation into Dutch is wanted, I would need the translated UI texts, unfortunately I do not speak the language.

Please check if it works now. Here is the [new version of the plugin](https://github.com/RolandDreger/indesign-openai/releases/tag/v1.4.0) or via Code -> Downlod ZiP on the main page.

**Comment by EstherRook** [comment]
Awesome, it works now! Indeed I had it set to Dutch, sorry I didn't think of that. English is fine this way. Cant wait to start experimenting with it, thanks!
